config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tops#index'
  resources :posts do
    resources :comments, only: :create
  end
  get '/category/:id', to: 'posts#index', as: 'category_image'
  resources :schedules, only: [:index, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '建造物' },
    { id: 3, name: 'ホテル,旅館' },
    { id: 4, name: 'グルメ,料理' },
    { id: 5, name: '自然' },
    { id: 6, name: '世界遺産' },
    { id: 7, name: 'ショップ' },
    { id: 8, name: 'アクセサリー,雑貨' },
    { id: 9, name: 'スポーツ' },
    { id: 10, name: 'ビーチ' },
    { id: 11, name: '人々' },
    { id: 12, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :posts

  end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true 
end

app/models/post.rb
class Post < ApplicationRecord  
  belongs_to :user
  has_many :comments
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category, :public

  validates :place, presence: true
  validates :category_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :public_id, numericality: { other_than: 1, message: "can't be blank" }  
end

app/models/public.rb
class Public < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '全て公開'},
    { id: 3, name: '友達公開' },
    { id: 4, name: '自分のみ' },
  ]

  include ActiveHash::Associations
  has_many :posts
  
  end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :region, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :schedules
         
  validates :nickname, presence: true
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    Comment.create(comment_params)
    redirect_to "/posts/#{comment_params[:post_id]}"
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:id]
      @posts = Post.where(category_id: params[:id]).order(created_at: :desc)
    else
      @posts = Post.all.order(created_at: :desc)
    end
  end

  def new
    @post = Post.new
  end 

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    category_id = post.category_id
    post.destroy
    redirect_to category_id ? category_image_path(category_id) : posts_path
  end
  
  private

  def post_params
    params.require(:post).permit(:image, :place, :content, :category_id, :public_id).merge(user_id: current_user.id)
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

  def index
    @schedules = Schedule.all
    @schedule = Schedule.new
  end

  def new
    @schedule = Schedule.new
  end

  def create
    Schedule.create(schedule_params)
    redirect_to schedules_path
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      redirect_to schedules_path
    else
      render 'edit'
    end
  end

  private

  def schedule_params
    params.require(:schedule).permit(:title, :region, :start_time, :end_time, :budget).merge(user_id: current_user.id)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WanderList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<body class="post-new">
  <div class="new-wrap">
    <div class="post-content">
      <%= form_with model: @post, class: "post-form", local: true do |f| %>
        <div class="box-wrap">
          <section class="form-section">
            <div class="section-header"></div>
            <div class="form-section-wrap">
              <div class="post-title">編集しよう</div>
            </div> 
          </section>
          
           <%= render 'shared/error_messages', model: f.object %>

          <section class="form-section">
            <div class="form-section-wrap">
              <div class="item-name">
                好きな画像・動画
                <span class="not_required">任意</span>
              </div>
              <%= f.file_field :image, class:"posts-text",id:"item-image" %>
            </div>
          </section>
          <section class="form-section">
            <div class="form-section-wrap">
              <div class="item-name">
                場所名
                <span class="required">必須</span>
              </div>
              <%= f.text_area :place, class:"posts-place", id:"post-place", placeholder:"場所名（必須 40文字まで)", maxlength:"40" %>
            </div>
          </section>
          <section class="form-section">
            <div class="form-section-wrap">
              <div class="item-name">
                テキスト
                <span class="not_required">任意</span>
              </div>
              <%= f.text_area :content, class:"posts-text", id:"post-info", placeholder:"場所の説明や情報（任意 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
            </div>
          </section>
          <section class="form-section">
            <div class="form-section-wrap">
              <div class="item-name">
                カテゴリー
                <span class="required">必須</span>
              </div>
              <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"post-category"}) %>
            </div>
          </section>
          <section class="form-section">
            <div class="form-section-wrap">
              <div class="item-name">
                公開範囲
                <span class="required">必須</span>
              </div>
              <%= f.collection_select(:public_id, Public.all, :id, :name, {}, {class:"select-box", id:"post-public"}) %>
            </div>
          </section>
        </div>
        <div class="post-btn-contents">
          <%= f.submit "更新する" ,class:"post-btn" %>
          <%#=link_to '<< back', root_path, class:"back-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</body>

app/views/posts/index.html.erb
<%= render "shared/header" %>

<%# 投稿一覧 %>
<div class="post-contents-main">
  <select class=public-lists>
    <option><%= link_to "全て公開", '#', class:"public-list", data: {filter: "all"} %></option>
    <option><%= link_to "友達公開", '#', class:"public-list", data: {filter: "friends"} %></option>
    <option><%= link_to "自分のみ", '#', class:"public-list", data: {filter: "me"} %></option>
  </select>

    <% if params[:id] && @posts.any? %>
      <div class="subtitle">
        <h2 class="category-name"><%= @posts.first.category.name %></h2>
      </div>
    <% end %>


    <ul class='item-lists'>
      <% @posts.each do |post| %>
         <%= link_to post.user.nickname,'#', class:"img-user" %>
        <li class='list'>
          <% if post.image.attached? %>
            <%= link_to image_tag(post.image, class:"category-images"), post_path(post.id) %>
          <% elsif %>
            <%= link_to image_tag('noimage.png', class:"category-images"), post_path(post.id)%>
          <% end %>
          <div class="img-detail">
            <p class="img-place"><%= post.place %></p>
            <p class="img-content"><%= post.content %></p>
          </div>
        <li>
        <div class="good-answers">
          <P class="good">いいねボタン</p>
          <P class="favorite">お気に入りボタン</p>         
        </div>
      <% end %>
    </ul>
</div>

  <%# /投稿一覧 %>
  


<%= render "shared/footer" %>

app/views/posts/new.html.erb
<body class="post-new">
  <div class="new-wrap">
    <div class="post-content">
      <%= form_with model: @post, class: "post-form", local: true do |f| %>
        <div class="box-wrap">
          <section class="form-section">
            <div class="section-header"></div>
            <div class="form-section-wrap">
              <div class="post-title">好きなものを投稿しよう</div>
            </div> 
          </section>
          
           <%= render 'shared/error_messages', model: f.object %>

          <section class="form-section">
            <div class="form-section-wrap">
              <div class="item-name">
                好きな画像・動画
                <span class="not_required">任意</span>
              </div>
              <%= f.file_field :image, class:"posts-text",id:"item-image" %>
            </div>
          </section>
          <section class="form-section">
            <div class="form-section-wrap">
              <div class="item-name">
                場所名
                <span class="required">必須</span>
              </div>
              <%= f.text_area :place, class:"posts-place", id:"post-place", placeholder:"場所名（必須 40文字まで)", maxlength:"40" %>
            </div>
          </section>
          <section class="form-section">
            <div class="form-section-wrap">
              <div class="item-name">
                テキスト
                <span class="not_required">任意</span>
              </div>
              <%= f.text_area :content, class:"posts-text", id:"post-info", placeholder:"場所の説明や情報（任意 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
            </div>
          </section>
          <section class="form-section">
            <div class="form-section-wrap">
              <div class="item-name">
                カテゴリー
                <span class="required">必須</span>
              </div>
              <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"post-category"}) %>
            </div>
          </section>
          <section class="form-section">
            <div class="form-section-wrap">
              <div class="item-name">
                公開範囲
                <span class="required">必須</span>
              </div>
              <%= f.collection_select(:public_id, Public.all, :id, :name, {}, {class:"select-box", id:"post-public"}) %>
            </div>
          </section>
        </div>
        <div class="post-btn-contents">
          <%= f.submit "投稿する" ,class:"post-btn" %>
          <%=link_to '<< back', root_path, class:"back-btn" %>
        </div>
      <% end %>
    </div>
  </div>
</body>

app/views/posts/show.html.erb
<%= render "shared/header" %>

<div class="contents_row">
  <%= link_to '<<一覧へ戻る', 'javascript:history.back()', class:"post_back" %>
  <div class="content_post">
    <div class="more">
      <% if @post.image.present? %>
        <span><%= image_tag @post.image %></span>
      <% else %>
        <%= image_tag 'noimage.png' %>
      <% end %>
      <% if user_signed_in? && current_user.id == @post.user_id %> 
      <ul class="more_list">
        <li>
          <%= link_to '編集', edit_post_path(@post.id), class:"more_list_edit", method: :get %>
        </li>
        <li>
          <%= link_to '削除', post_path(@post.id), class:"more_list_delete", method: :delete %>
        </li>
      </ul>
      <% end %>
    </div>
    
    <div class="more_content">
      <p class="img-place"><%= @post.place %></p>
      <p class="img-content"><%= @post.content %></p>
    </div>
    <div class="more-comments">
      <p class="img-comment">コメント</p>
      <% if user_signed_in? %>
        <%= form_with(model: [@post, @comment], local: true) do |form| %>
          <%= form.text_area :text, placeholder: "コメントする", rows: "3" %>
          <%= form.submit "SEND" %>
        <% end %>
      <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
      <% end %>
      <div class="comments">
        <h4>＜コメント一覧＞</h4>
        <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}", class:"comment_user" %>：</strong>
          <%= comment.text %>
        </p>
        <% end %>
      </div>
    </div>
  </div>
</div>



          
<%= render "shared/footer" %>

app/views/schedules/edit.html.erb
 <%= form_with(model: @schedule, local: true) do |form| %>

        <div class="sche_title_detail">
          <div class="form-tag">タイトル</div>
          <%= form.text_field :title %>
        </div>

         <div class="sche_budget">
          <div class="form-tag">予算</div>
          <%= form.text_field :budget %>円
        </div>

        <div class="sche_region">
          <div class="form-tag">地域</div>
          <%= form.select :region, options_for_select([['北アメリカ', 'north-america'], ['南アメリカ', 'south-america'], ['ヨーロッパ', 'europe'], ['アフリカ', 'africa'], ['オセアニア', 'oceania'], ['東アジア', 'east-asia'], ['東南アジア', 'southeast-asia'], ['中央・中東アジア', 'central-middleeast-asia'], ['日本', 'japan']]) %>
        </div>

        <div class="shce_time">
          <div class="form-tag">開始日</div>
          <%= form.date_select :start_time %>
        </div>

        <div class="sche_time">
          <div class="form-tag">終了日</div>
          <%= form.date_select :end_time %>
        </div>

        <div class="sche_submit">
          <%= form.submit %>
        </div>
      <% end %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<%= render "shared/header" %>

<div class="schedule_display">
  <div class="schedule_main">
    <div class="col-md-4">
      <div class="table">
        <div class="sche-title">
            <div class="sche_title_plan">タイトル日程</div>
        </div>
      </div>

      <%= form_with(model: @schedule, local: true) do |form| %>

        <div class="sche_title_detail">
          <div class="form-tag">タイトル</div>
          <%= form.text_field :title %>
        </div>

         <div class="sche_budget">
          <div class="form-tag">予算</div>
          <%= form.text_field :budget, class:"sche_budget_sp"%>円
        </div>

        <div class="sche_region">
          <div class="form-tag">地域</div>
          <%= form.select :region, options_for_select([['北アメリカ', 'north-america'], ['南アメリカ', 'south-america'], ['ヨーロッパ', 'europe'], ['アフリカ', 'africa'], ['オセアニア', 'oceania'], ['東アジア', 'east-asia'], ['東南アジア', 'southeast-asia'], ['中央・中東アジア', 'central-middleeast-asia'], ['日本', 'japan']]) %>
        </div>

        <div class="shce_time">
          <div class="form-tag">開始日</div>
          <%= form.date_select :start_time %>
        </div>

        <div class="sche_time">
          <div class="form-tag">終了日</div>
          <%= form.date_select :end_time %>
        </div>

        <div class="sche_submit">
          <%= form.submit %>
        </div>
      <% end %>
   </div>

      <div class="col-md-8">
        <%= month_calendar events: @schedules do | date, schedules | %>
          <%= date.day %>
          <% schedules.each do |schedule| %>
            <div class="schedule-option-<%= schedule.region.parameterize %>">
              <%= link_to schedule.title, "#", class: 'sche_title_deco'%>
            </div>
          <% end %>
        <% end %>
        <br>

        <table class="table-bordered">
          <div class="schedule_list">今後の予定一覧</div>
			    <thead>
            <tr>
              <th>タイトル</th>
              <th>予算（円）</th>
              <th>地域</th>
              <th>開始日</th>
              <th>終了日</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <div class="sche-plan">
            <% @schedules.each do |plan| %>
              <tbody>
                <tr>
                  <td><%= link_to plan.title, '#' ,class:'sche_plan_title'%></td>
                  <td><%= plan.budget.to_s.gsub(/(\d)(?=(\d{3})+(?!\d))/, "\\1,")%></td>
                  <td><%= plan.region%></td>
                  <td><%= plan.start_time.strftime("%Y-%m-%d")%></td>
                  <td><%= plan.end_time.strftime("%Y-%m-%d")%></td>
                  <td><%=link_to "編集" , edit_schedule_path(plan.id),:class=>"btn04"  %></td>
                  <td><%=link_to "削除", '#' , method: :delete , data: {confirm:"削除しますか"} ,:class=>"btn03"%></td>
                </tr>
              </tbody>
            <% end %>
          </div>
  		  </table>
      </div>
</div>
</div>
<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-logo">WanderList</div>
</footer>

app/views/shared/_header.html.erb
<header class="top-page-header">
  <div class="heading">
    <h1 class="logo"><a href="/">WanderList</a></h1>  
  </div>

  <div class="nav">
    <ul class="nav-lists" >
      <div class="lists_left">
      <li><%= link_to '投稿', new_post_path, class: "nav-lists_list", id: "list1" %></li>
      <li><%= link_to 'スケジュール帳', schedules_path, class: "nav-lists_list", id: "list2" %></li>
      <li><%= link_to '地図', '#', class: "nav-lists_list", id: "list3" %></li>
      <li><%= link_to 'お気に入り', '#', class: "nav-lists_list", id: "list4" %></li>
      <li><%= link_to '友達リスト', '#', class: "nav-lists_list", id: "list5" %></li>
      </div>
      <div class="lists_right">
        <% if user_signed_in? %>
          <li><%= link_to current_user.nickname, '#', class: "user-nickname" %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout"%></li>
        <% else %>
          <li><%= link_to 'ログイン', new_user_session_path, class: "login"%></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up"%></li>
        <% end %>
      </div>
    </ul>
  </div>
</header>

app/views/tops/index.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="title-contents">
    <h1 class='service-title'>さあ、飛び出そう</h1>
    <p class='service-explain'>
      友達と感動のシェアを
    </p>
  </div>
  <section class="post-home">
    <div class="post-home-space">
      <h2 class="post-home-title">友達の投稿をカテゴリーから探してみよう！</h2>
    </div>
    <ul class="post-home-pic">
      <div class="home-pic-caption">
        <li><%= link_to image_tag("スカイツリpublicdomainq-0017061gbe.jpg", category_id: 2, class:"home-pic-building"), "/category/2" %></li>
        <p class="home-pic-title">建造物</p>
      </div>

      <div class="home-pic-caption">
        <li><%= link_to image_tag("ホテルd77eaad4b33aefe9d8e0980f3aad4f12_t.jpg", category_id: 3, class:"category-picture"),  "/category/3" %></li>      
        <p class="home-pic-title">ホテル,旅館</p>
      </div>

      <div class="home-pic-caption">
      <li><%= link_to image_tag("グルメadpDSC_1803-.jpg", category_id: 4, class:"category-picture"),  "/category/4" %></li>
        <p class="home-pic-title">グルメ,料理</p>
      </div>

      <div class="home-pic-caption">
        <li><%= link_to image_tag("自然photo0000-2033.jpg", category_id: 5, class:"category-picture"),  "/category/5" %></li>
        <p class="home-pic-title">自然</p>
      </div>

      <div class="home-pic-caption">
       <li><%= link_to image_tag("世界遺産4029580878_ea807804e5.jpg",category_id: 6, class:"category-picture"),  "/category/6" %></li>
        <p class="home-pic-title">世界遺産</p>
      </div>

      <div class="home-pic-caption">
        <li><%= link_to image_tag("ショップcac6ac2163e673609b90372bf628cb71_t.jpg", category_id: 7, class:"category-picture"),  "/category/7" %></li>  
        <p class="home-pic-title">ショップ</p>
      </div>

      <div class="home-pic-caption">
        <li><%= link_to image_tag("雑貨089_2048-1024x683.jpg", category_id: 8, class:"category-picture"),  "/category/8" %></li>
        <p class="home-pic-title">アクセサリー,雑貨</p>
      </div>

      <div class="home-pic-caption">
        <li><%= link_to image_tag("depositphotos_183057156-stock-photo-sports-tools-on-green-grass.jpg", category_id: 9, class:"category-picture"),  "/category/9" %></li>
        <p class="home-pic-title">スポーツ</p>
      </div>

      <div class="home-pic-caption">
        <li><%= link_to image_tag("ビーチpr00488.jpg", category_id: 10, class:"category-picture"),  "/category/10" %></li>
        <p class="home-pic-title">ビーチ</p>
      </div>

      <div class="home-pic-caption">
        <li><%= link_to image_tag("人々2019-10-05-17.28.25-1024x768.jpg", category_id: 11, class:"category-picture"),  "/category/11" %></li>
        <p class="home-pic-title">人々</p>
      </div>

      <div class="home-pic-caption">
        <li><%= link_to image_tag("その他dscn0128.jpg", category_id: 12, class:"category-picture"),  "/category/12" %></li>
        <p class="home-pic-title">その他</p>
      </div>
      
      <div class="home-pic-caption">
        <li><%= link_to image_tag("allダウンロード.jpg", class:"category-picture"), posts_path %></li>
        <p class="home-pic-title">ALL</p>
      </div>
    </ul>
  </section>
  
</div>

<%= render "shared/footer" %>